config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists do
    resources :movies, only: [:new, :index, :create, :update]
    resources :bookmarks, only: [:new, :index, :create, :update]
  end
  # Defines the root path route ("/")
  root to: "lists#index"
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, :list, presence: true

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    @bookmark.save
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy!
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :bookmark_ids, :movie_ids, :comment, :movie_id)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Modify the name of your list", class: "btn btn-primary" %>
<% end %>

<%= link_to "Delete your list",
  list_path(@list.id),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

app/views/lists/index.html.erb
<h1>Your Lists</h1>

<ol>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list.id) %></li>
  <% end %>
</ol>

<p><%= link_to "Create a new List", new_list_path() %></p>

app/views/lists/new.html.erb
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit new list", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h1 class="text-center"><%= @list.name %></h1>
<div class="container text-end">
  <a class="btn btn-outline-danger btn-sm text-hover-light" href="<%=edit_list_path(@list)%>" role="button">Edit</a>
  <a class="btn btn-outline-danger btn-sm text-hover-light" href="<%=lists_path()%>" role="button">Back</a>
</div>

<h2 class="text-center"> Bookmarks </h2>

<div class="container">
  <div class="card-group">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card">
        <img class="card-img-top" src="<%= bookmark.movie.poster_url %>" alt="">
        <div class="card-body">
          <h2 class="card-title"><%= bookmark.movie.title %></h2>
          <p>Rating: <%= bookmark.movie.rating %></p>
          <p class="card-text"><em><%= bookmark.movie.overview %></em></p>
          <p class="card-footer"><strong>Your comment is:  </strong>"<%= bookmark.comment %>"</p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container mt-5 mb-5">
  <h2>Add a movie to your list</h2>

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit %>
  <% end %>
</div>

app/views/movies/index.html.erb
<h1>All Movies</h1>

<ol>
  <% @movies.each do |movie| %>
    <li><%= link_to movie.title, movie_path(movie.id) %></li>
  <% end %>
</ol>

app/views/movies/show.html.erb
<img src="<%= @movie.poster_url %>" alt="">
<h2><%= @movie.title %></h2>
<p><%= @movie.overview %></p>
<p><%= @movie.rating %></p>